#define TYPE_GATEWAY 128
#define TYPE_TODEFINE1 64
#define TYPE_TODEFINE2 32
#define TYPE_TODEFINE3 16
#define TYPE_TODEFINE4 8
#define TYPE_TODEFINE5 4
#define TYPE_IRRIG 2
#define TYPE_BULB 1

#define TYPE_ERROR 0